## The two functions here together return the inverse of a matrix.
## Once an inverse of a particular matrix has been calculated, it is stored
## in the cache. If no changes have been made to the matrix, the cached
## inverse is returned each time the cacheSolve function is called.


## ----------------  makeCacheMatrix --------------------
## INPUT: an invertible matrix 
## OUTPUT: a list of the following functions associated with the matrix: 
##    set - stores the input matrix in the cache
##    get - returns the input matrix from cache
##    setinv - stores the inverse of the matrix in cache
##    getinv - returns the inverse of the matrix from cache

makeCacheMatrix <- function(x = matrix()) {
  i <- NULL
  set <- function(y) {
    x <<- y
    i <<- NULL
  }
  get <- function() x
  setinv <- function(inv) i <<- inv
  getinv <- function() i
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)

}


## --------------------  cacheSolve -----------------------
## INPUT: x - a list of functions generated by makeCacheMatrix associated with 
##        an invertible matrix
## OUTPUT: the inverse of the matrix
## NOTE: the inverse is only calculated if it is not found in the cache

cacheSolve <- function(x, ...) {
## Return a matrix that is the inverse of 'x'
  
  i <- x$getinv()
  ## First check to see if the inverse has already been calculated and stored in the
  ## cache (returned from the call to getinv). If the return value is not null
  ## return the cached inverse.
  if(!is.null(i)) {
    message("getting cached inverse")
    return(i)
  }
  
  ## The inverse has not been calculated, so get the matrix, calculate the inverse
  ## using solve, then store the inverse in the cache by calling setinv.
  data <- x$get()
  i <- solve(data, ...)
  x$setinv(i)
  i
}
